config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'get_coordinates', to: 'home#get_coordinates'
  get 'get_weather', to: 'home#get_weather'
  get 'show', to: 'home#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/weather.rb
# frozen_string_literal: true

# Class representing weather details for better abstraction
class Weather
  def initialize(data)
    # Use 'with_indifferent_access' for consistent access to data keys as symbols or strings
    @data = data.with_indifferent_access
  end

  # Method to get the URL for the weather icon
  def icon_url
    "https://openweathermap.org/img/wn/#{current_weather[:icon]}@2x.png"
  end

  # Method to get the overall weather status
  def status
    current_weather[:main]
  end

  # Method to get the detailed weather description
  def description
    current_weather[:description]
  end

  # Method to get the current temperature
  def current_temperature
    data.dig(:main, :temp)
  end

  # Method to get the feels-like temperature
  def feels_like_temperature
    data.dig(:main, :feels_like)
  end

  # Method to get the wind speed
  def wind_speed
    data.dig(:wind, :speed)
  end

  # Method to get the high temperature
  def high_temperature
    data.dig(:main, :temp_max)
  end

  # Method to get the low temperature
  def low_temperature
    data.dig(:main, :temp_min)
  end

  # Method to get the city name
  def city
    data[:name]
  end

  private

  attr_reader :data

  # Method to get the details of the current weather
  def current_weather
    @current_weather ||= data[:weather].first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include Geocoder

  # Action to get coordinates based on the provided address
  def get_coordinates
    address = params[:address]
    results = Geocoder.search(address)

    if results.present?
      coordinates = results.first.coordinates
      latitude = coordinates[0]
      longitude = coordinates[1]
      get_weather(latitude, longitude)

      return if performed?

      render :show
    else
      # If no coordinates found, set flash error and redirect to root_path
      flash[:error] = 'Location not found. Please enter a valid address.'
      redirect_to root_path
    end
  end

  # Private method to get weather information based on latitude and longitude
  private

  def get_weather(latitude, longitude)
    if latitude.present? && longitude.present?
      cache_key = "coordinates_#{longitude}_#{latitude}"
      @cached_indicator = Rails.cache.exist?(cache_key)

      if @cached_indicator
        # Use cached data if available
        @data = Rails.cache.read(cache_key)
      else
        # Fetch current weather data using a service and store it in the cache
        @data = CurrentWeatherService.new(latitude: latitude, longitude: longitude, units: 'imperial').call
        Rails.cache.write(cache_key, @data, expires_in: 30.minutes)
      end
      
      if @data.present? && @data['weather'].present?
        # Create a Weather object for better abstraction and easy access to weather details
        @weather = Weather.new(@data)
      else
        # If weather data is invalid, set flash error and redirect to root_path
        flash[:error] = 'Invalid weather data'
        redirect_to root_path
      end
    else
      # If location is invalid, set flash error and redirect to root_path
      flash[:error] = 'Invalid location'
      redirect_to root_path
    end
  rescue StandardError => e
    # Handle any unexpected errors, set flash error, and redirect to root_path
    flash[:error] = e.message
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="d-flex flex-column align-items-center justify-content-center text-center" style="margin-top: 60px; margin-bottom: 10px;">   
  <h1 class="mb-3">ForecastNow</h1>
  <%= image_tag('weather_img.png', alt: 'Weather Image', class: 'w-50 mx-auto') %>
</div>

app/views/home/show.html.erb
<div class="card text-center col-6 mx-auto custom-card custom-light-blue-bg">
  <div class="card-header">
    <h4 class="card-title">Weather Information</h4>
  </div>
  <div class="card-body custom-bg-light" >
    <% if @cached_indicator %>
      <p class="text-white">>>Data retrieved from cache<<</p>
    <% else %>
      <p class="text-white">>>Fresh data retrieved<<</p>
    <% end %>

    <% if @weather.present? %>
      <h2><i class="fa-solid fa-location-dot"></i></i> <%= @weather.city %></h2>
      <img src="<%= @weather.icon_url %>" alt="Weather Icon"/>
      <p class="card-text" style="font-size: 48px;"><%= @weather.current_temperature %> ° F</p>
      <p class="card-text"><span style="font-size: 14px;">Feel like:</span> <%= @weather.feels_like_temperature %> ° F</p>
      <p class="card-text"><%= @weather.description %></p>
      <p class="card-text" style="font-size: 14px;">Wind speed: <%= @weather.wind_speed %> km/h</p>   
      <p>H: <%= @weather.high_temperature %> | <span style="margin-left: 5px;">L: <%= @weather.low_temperature %></span></p>
    <% else %>
      <p class="card-text">No weather data available.</p>
    <% end %>
  </div>
  <div class="card-footer text-body-secondary">
    <%= Time.now.strftime("%A, %B %d") %> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forecast Now</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/svg+xml" href="/assets/sun-regular.svg" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/717a07a2d7.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/search" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_search.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>
<nav class="navbar navbar-expand-lg p-3 mb-2 bg-info text-white">
  <div class="container-fluid">
    <a class="navbar-brand text-white text-decoration-underline" href="<%= root_path %>">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
      </ul>
      <%= form_tag(get_coordinates_path, method: :get, class: "d-flex justify-content-center") do %>
        <%= text_field_tag :address, nil, placeholder: 'Enter address', class: "form-control me-2" %>
        <%= submit_tag 'Get Weather', class: "btn btn-outline-light" %>
      <% end %> 
    </div>
  </div>
</nav>